#!/bin/bash

options=(
    style=round
    width=2.0
    hidpi=on
    # active_color=0xff8bd6b6   # Green
    # active_color=0xffffffff   # Black
    inactive_color=0x00000000 # Black
    # active_color="gradient(top_left=0xff30c0f0,bottom_right=0xff02f091)"
    # inactive_color=0xff3e4345
    # active_color=0xffB3EBF2
    # active_color=0xff80ef80 # Pastel green
    # active_color="gradient(top_left=0xffa6c5e5,bottom_right=0xfff0a8e0)"
    # active_color=0xffe2e2e3 # White
    # active_color=0xffeed49f
    order="a"
    # active_color=0xff66f7ff
    # active_color=0xffc6a0f6
    # active_color=0xffffc457
    # active_color=0xffd857ff
    # active_color=0xffe188fc
    # active_color=0xff79241f
    active_color=0xffffffff
    # active_color=0xffc4a7e7 # Rose-pine Magenta
    # active_color=0xfff6c177 # Rose-pine Gold
    # active_color=0xffcf91b5 # Rose-pine Rose
    # inactive_color=0xff494d64
    # inactive_color=0xff696d84
    # inactive_color="gradient(top_left=0xffE0E0E5,bottom_right=0xffF5E8D3)"
)

borders "${options[@]}"
